spring:
    application:
        name: lclgateway
server:
    port: 8888

lclrpc:
    lclregistry:
        servers: http://localhost:8484

logging:
    level:
        org:
            springframework:
                web: DEBUG

